### PR TITLE
EfM Sync 20.11.2023

### PR DESCRIPTION
**Pull request by ChrisMarsh82**
Sync latest content with timestamps

### CODE REVIEW

**Review by esmeetewinkel — APPROVED** [review]
Content sync looks fine and app is working.

@cabrinenyona  when testing the app on the web preview link I can't see the timestamps working for some reason, so would be good if you could double check.

**Comment by cabrinenyona** [comment]
@esmeetewinkel I will have a look into it.

**Comment by cabrinenyona** [comment]
@esmeetewinkel , The sync seems to have gone through as you mentioned earlier and I have checked through the files(templates) where the timestamps have been stored on GitHub, and nothing looks a miss. On the other hand, when I run yarn workflow sync on VS the 6 changed files resurface and a running git pull wouldn't be successful as there might not be a specified upstream branch for my local branch allegedly. 

image
image

**Comment by esmeetewinkel** [comment]
@cabrinenyonaThanks. It makes sense you don't see the changes yet on VS Code, because there you are probably looking at the `main` branch, which doesn't have this change yet because the PR is still open. Once this PR is merged you should no longer have "6 changed files" appear when you sync. 

I'll merge it now, can you then confirm on the EFM web preview https://early-family-math.web.app/ that this is working as expected?

**Comment by cabrinenyona** [comment]
@esmeetewinkel The timestamps have come through successfully.
image

**Pull request merged**
